title: Sairam Tabibu
url: "https://tabibusairam.github.io"
baseurl: ""


markdown: kramdown

tracking_id: #


sass:
    style: compressed
    sass_dir: _sass

include: ["_pages"]

github_username:  tabibusairam
linkedin_username: sairamtabibu
facebook_username: sairamtabibu

