title: Sairam Tabibu
author: Sairam Tabibu
url: "https://tabibusairam.github.io"
baseurl: ""

description: Sairam Tabibu's website

markdown: kramdown

# google_analytics_tracking_id: UA-109052064-1

sass:
    style: compressed
    sass_dir: _sass

include: ["_pages"]

github_username:      tabibusairam
linkedin_username:    sairamtabibu
# quora_username:       Vikram-Voleti
# wordpress_username:   vikramvoleti
facebook_username:    sairamtabibu
#twitter_username:     vikky2904
#google_plus_username: vikky2904
